### PR TITLE
Sort Events feature

### LINKED ISSUE #56: Sort event based on date and time

### PR DESCRIPTION
**Pull request by lhy-hoyin**
- Make `Event` comparable (via Date and Start Time) - chronological order [committed previously]
- Add a `SortCommand` to initiate a sorting of all events in the scheduler
- Add 5 test cases for `SortCommand`
  - Test general sorting in order
  - Test sorting events of same date, different start time
  - Test sorting events of different date, same start time
  - Test sorting events of "opposing" date and start time
 
This PR closes #56.

### CODE REVIEW

**Review by anthonynmh — DISMISSED** [review]
Test class is comprehensive, nice work. LGTM :)

**Comment by lhy-hoyin** [comment]
Merged new changes to master to this branch.

**Review by BigheartSmallbrain — COMMENTED** [review]
I supposed there's a need for test for commandParser here?

**Review by BigheartSmallbrain — APPROVED** [review]
Everything LGTM now :).

**Pull request merged**
